version: '2'
services:
  jenkins:
    image: 'framework/jenkins:2-ol-7'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/deepthi'

volumes:
  jenkins_data:
    driver: local
 
